name: Complete CI Workflow
on:
  push:
    branches:
      - stage
      - prod
  pull_request:
    branches:
      - stage
      - prod
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: my-ci-workflow-${{ github.ref_name }}.

jobs:
   get-environment:
    name: Get Environment name
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-environment-name.outputs.value }}
    steps:
      - name: 
        id: get-environment-name
        uses: haya14busa/action-cond@v1
        with:
           cond: ${{ github.event_name == 'pull_request'}}
           if_true: ${{ github.base_ref }}
           if_false: ${{ github.ref_name }} 
        # run: |
        #   if [[ "${{ github.ref_name }}" == "stage" ]]; then
        #     echo "environment=staging" >> $GITHUB_OUTPUT
        #   elif [[ "${{ github.ref_name }}" == "prod" ]]; then
        #     echo "environment=production" >> $GITHUB_OUTPUT
        #   else
        #     echo "environment=unknown" >> $GITHUB_OUTPUT
        #   fi