name: Complete CI Workflow
on:
  push:
    branches:
      - stage
      - prod
  pull_request:
    branches:
      - stage
      - prod
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: my-ci-workflow-${{ github.ref_name }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print event
        run: |
          echo "workflow triggered by event: ${{ github.event_name }}"
          echo "workflow triggered by action: ${{ github.event.action }}"
          echo "Started at: $(date)"

      - name: Wait for 120 seconds
        run: sleep 120

      - name: end
        run: |
          echo "Workflow completed at: $(date)"