name: Pull Request Validation

on:
  pull_request:
    branches:
      - dev
      - stage
      - prod
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: pr-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display GitHub Context
        run: |
          echo "Event Name : ${{ github.event_name }}"
          echo "Action     : ${{ github.event.action }}"
          echo "Source     : ${{ github.head_ref }}"
          echo "Target     : ${{ github.base_ref }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
           terraform plan \
             -var-file=Infrastructure/environments/${{ github.base_ref }}.tfvars \
             -out=tfplan